# 프로덕션 환경 설정
spring:
  # PostgreSQL (프로덕션)
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:testdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA 프로덕션 설정
  jpa:
    hibernate:
      ddl-auto: validate  # 프로덕션에서는 스키마 검증만
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Redis 프로덕션 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

# 프로덕션 로깅 설정
logging:
  level:
    com.agentica.user: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    
# JWT 프로덕션 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity-time: 1800000   # 30분 (보안상 짧게)
  refresh-token-validity-time: 86400000 # 1일
