spring:
  application:
    name: user-test
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  # 테스트 환경에서는 메일 발송 비활성화
  mail:
    host: localhost
    port: 25
    username: test@test.com
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  # 테스트 환경에서 OAuth2 설정 (더미 값)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-google-client-id
            client-secret: test-google-client-secret
            scope:
              - email
              - profile
          naver:
            client-id: test-naver-client-id
            client-secret: test-naver-client-secret
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          kakao:
            client-id: test-kakao-client-id
            client-secret: test-kakao-client-secret
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: client_secret_post
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: test-jwt-secret-key-for-testing-12345678901234567890
  access-token-validity-time: 3600000  # 1시간 (밀리초)
  refresh-token-validity-time: 86400000  # 24시간 (밀리초)

logging:
  level:
    com.agentica.user: DEBUG
    org.springframework.security: DEBUG
